### PR TITLE
Added examples for Scorpion programming language

### PR DESCRIPTION
**Pull request by AndroDevcd**
Hello, I am new to this so I am not sure what I have to do but I would like for github to recognize that my language source is present. 

The language is called Scorpion, and its a low level bare metal programming language that allows you to closely program the physical hardware on a device, or at least "emulate" that affect. The languages has 2 types of important files:

Scorpion Source: or ".ss" files will hold the somewhat high level source code written in Scorpion.
Scorpion Executable: or ".b" a binary file that contains only 1's 0's and white-space.

I would like to request for you to notice all my scorpion source files ".ss" as well as my executable files ".b" in my repo.

If you need any additional information please let me know. Also I have added a syntax coloring .xml file in the samples folder for syntax coloring.

### CODE REVIEW

**Comment by pchaigno** [comment]
Please see the [requirements to add a new language](https://github.com/pchaigno/linguist/blob/master/CONTRIBUTING.md#adding-a-language).

**Comment by AndroDevcd** [comment]
How do I add my grammer, Ive added an entry for my language in languages.yml, and added my repo as a submodule?

**Comment by pchaigno** [comment]
Do you have a search result showing as many examples of `.ss` files as possible?

**Comment by AndroDevcd** [comment]
I do not when I use the web browser because you haven't merged the request yet

**Comment by AndroDevcd** [comment]
I have added a few good examples in my language though.

**Comment by pchaigno** [comment]
That won't be sufficient. You have to show that the language is in use in hundreds of repository to add it to linguist.

**Comment by AndroDevcd** [comment]
Oh ok, Ill come back when it is.

**Comment by pchaigno** [comment]
Okay :-)

**Pull request closed without merging**
